server:
  port: 7002


####################################Spring配置############################################
spring:
  application:
    name: hanghua-mail

  #邮件
  mail:
    #smtp服务主机
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    #编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: ximenalang@foxmail.com
    #授权码
    password: lrhfatkallvtbcia
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #redis缓存配置
  redis:
    # Redis数据库索引（默认为0
    database: 0
    # Redis服务器地址
    host: 49.235.119.174
    # Redis服务器连接端口
    port: 6666
    # Redis服务器连接密码（默认为空
    password: 1234567
    #连接超时(ms)
    timeout: 5000
    #jedis连接池
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -2
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

  #微服务配置
  cloud:
      nacos:
        discovery:
          # 指定nacos server的地址
          server-addr: 49.235.119.174:8848



