server:
  port: 8080


spring:
  application:
    name: hanghua-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 49.235.119.174:8848

    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      # id为路由的唯一标识
      # uri为目标服务地址,lb表示从注册中心订阅服务
      # predicates为路由条件，接受一个输入参数，返回一个布尔值结果。若为真，则路由匹配，目标URI会被访问。
      routes:
        - id: admin-service
          uri: lb://hanghua-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        - id: article-service
          uri: lb://hanghua-article
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix=1

        - id: comment-service
          uri: lb://hanghua-comment
          predicates:
            - Path=/comment/**
          filters:
            - StripPrefix=1

        - id: im-service
            uri: lb://hanghua-im
            predicates:
              - Path=/im/**
            filters:
              - StripPrefix=1

        - id: mail-service
            uri: lb://hanghua-mail
            predicates:
              - Path=/mail/**
            filters:
              - StripPrefix=1

        - id: auth-service
            uri: lb://hanghua-auth
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1
