Spring:
  #redis缓存配置
  redis:
    # Redis数据库索引（默认为0
    database: 0
    # Redis服务器地址
    host: 49.235.119.174
    # Redis服务器连接端口
    port: 6666
    # Redis服务器连接密码（默认为空
    password: 1234567
    #连接超时(ms)
    timeout: 5000
    #jedis连接池
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -2
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0


swagger:
  name: 行话
  description: 行业内容社区


# swagger3.0配置
springfox:
  documentation:
    swagger-ui:
      enabled: false


