##################################基本环境配置#############################################
server:
  port: 7001







##################################Spring环境配置###########################################
spring:
  application:
    #服务名
    name: hanghua-sso


  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xiashuo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234567
    #druid连接池
    druid:
      #初始化大小、最大值、最小值
      initial-size: 5
      min-idle: 5
      max-active: 20
      #连接等待超时(ms)
      max-wait: 6000
      #检测间隔时间(ms)
      time-between-eviction-runs-millis: 6000
      #连接最小生存时间(ms)
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #PScache
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #SQL慢记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      #统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall,slf4j
      #监控拦截
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #监控视图配置
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单
        allow:
        #IP黑名单 (deny优先于allow)
        deny:
        #禁用重置
        reset-enable: false
        #监控登陆
        login-username: admin
        login-password: 123456


  #redis缓存配置
  redis:
    # Redis数据库索引（默认为0
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空
    password: 1234567
    #连接超时(ms)
    timeout: 5000
    #jedis连接池
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -2
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0








##########################################MyBatis配置##################################################

mybatis:
  #mapper文件路径
  mapper-locations: classpath:mapper/*.xml
  #entity映射包
  type-aliases-package: com.beetle.hanghuasso.mapper


























