##################################\u57FA\u672C\u73AF\u5883\u914D\u7F6E#############################################
server:
  port: 7003







##################################Spring\u73AF\u5883\u914D\u7F6E###########################################
spring:
  application:
    #\u670D\u52A1\u540D
    name: hanghua-article


  #\u6570\u636E\u6E90
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.119.174:6667/xiashuo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234567
    #druid\u8FDE\u63A5\u6C60
    druid:
      #\u521D\u59CB\u5316\u5927\u5C0F\u3001\u6700\u5927\u503C\u3001\u6700\u5C0F\u503C
      initial-size: 5
      min-idle: 5
      max-active: 20
      #\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6(ms)
      max-wait: 6000
      #\u68C0\u6D4B\u95F4\u9694\u65F6\u95F4(ms)
      time-between-eviction-runs-millis: 6000
      #\u8FDE\u63A5\u6700\u5C0F\u751F\u5B58\u65F6\u95F4(ms)
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #PScache
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #SQL\u6162\u8BB0\u5F55
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      #\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1
      filters: stat,wall,slf4j
      #\u76D1\u63A7\u62E6\u622A
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #\u76D1\u63A7\u89C6\u56FE\u914D\u7F6E
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP\u767D\u540D\u5355
        allow:
        #IP\u9ED1\u540D\u5355 (deny\u4F18\u5148\u4E8Eallow)
        deny:
        #\u7981\u7528\u91CD\u7F6E
        reset-enable: false
        #\u76D1\u63A7\u767B\u9646
        login-username: admin
        login-password: 123456


  #redis\u7F13\u5B58\u914D\u7F6E
  redis:
    # Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0
    database: 0
    # Redis\u670D\u52A1\u5668\u5730\u5740
    host: 49.235.119.174
    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    port: 6666
    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A
    password: 1234567
    #\u8FDE\u63A5\u8D85\u65F6(ms)
    timeout: 5000
    #jedis\u8FDE\u63A5\u6C60
    jedis:
      pool:
        # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236
        max-wait: -2
        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 10
        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 0

  #\u5FAE\u670D\u52A1\u914D\u7F6E
  cloud:
    nacos:
      discovery:
        # \u6307\u5B9Anacos server\u7684\u5730\u5740
        server-addr: 49.235.119.174:8848






##########################################MyBatis\u914D\u7F6E##################################################

mybatis:
  #mapper\u6587\u4EF6\u8DEF\u5F84
  mapper-locations: classpath:mapper/*.xml
  #entity\u6620\u5C04\u5305
  type-aliases-package: com.beetle.hanghuaarticle.mapper


























